### ISSUE TITLE
Adding the cookbook to supermarket

### ISSUE THREAD

**Issue by ffahimi** [wanelo-chef/pkgsrc#3]
Could you please add this cookbook to supermarket as we are implementing the berkshelf way?

For now the link is hard-coded inside berksfile. @bixu

**Comment by bixu** [comment]
@ffahimi, I'm guessing this will happen in a few hours at the earliest as the maintainers are on the US West Coast.

**Comment by bixu** [comment]
@sax @hjhart *bump*  :)

**Comment by sax** [comment]
https://supermarket.chef.io/cookbooks/pkgsrc
